server:
  port: 5004
  servlet:
    context-path: /test-bitcoin-pay

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test-bitcoin-pay?serverTimezone=Asia/Shanghai
    #    url: jdbc:log4jdbc:mysql://localhost:3306/test-bitcoin-pay?serverTimezone=Asia/Shanghai
    username: root
    password: mysqlmima123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database: mysql
    #    show-sql: true
    open-in-view: false
